---
title: "Untitled"
author: "Shankar K Shakya"
date: "December 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##

```{r, eval=FALSE, echo=TRUE}

rm(list = ls())
library(vcfR, quietly = T)
library(poppr, quietly = T)
library(ggplot2, quietly = T)
library(reshape2, quietly = T)

raw_vcf <- read.vcfR("Pcinna242.rmdup.gvcf2vcf.vcf.gz", verbose = FALSE)

sojae <- read.vcfR("Pcinna_sojae_1027var.gz")

source("R/subset_vcf2vcf.R")
vcf <- subset_vcf2vcf(raw_vcf, sojae)

#vcf <- vcf[ , -(grep("Rep2.fq|Rep3.fq", colnames(vcf@gt)))]

vcf <- vcf[ , -(grep("Rep2.fq|Rep3.fq|254-3579-WAus.fq", colnames(vcf@gt)))]

dp <- extract.gt(vcf, element = "DP", as.numeric=TRUE)
myMiss <- apply(dp, MARGIN = 2, function(x){ sum( is.na(x))} ) # number of NA per sample
myMiss <- myMiss / nrow(dp)
vcf@gt <- vcf@gt[, c(TRUE, myMiss < 0.1)]

dp <- extract.gt(vcf, element = "DP", as.numeric=TRUE)

check <- colMeans(dp, na.rm = T) >= 10
#ncol(vcf@gt[, c(TRUE, check)])
vcf@gt <- vcf@gt[, c(TRUE, check)]

vcf

Psojae <- sojae[ , c(1, 206)]

vcf@gt <- cbind(vcf@gt, Psojae@gt[, 2])


write.vcf(vcf, "Min10x_cov_203isolates_1027Variants.gz")



```




```{r}

library(vcfR, quietly = T)
library(poppr, quietly = T)
library(ggplot2, quietly = T)
library(reshape2, quietly = T)

vcf <- read.vcfR("Min10x_cov_203isolates_1027Variants.gz")

vcf <- extract.indels(vcf)

dp <- extract.gt(vcf, element = "DP", as.numeric=TRUE)
par(mar=c(12,4,4,2))
#boxplot(dp, col=2:8, las=3)
boxplot(dp, col=2:8, xaxt="n")
title(ylab = "Depth (DP)")


id <- unlist(strsplit(colnames(vcf@gt)[-1], split = ".fq"))
pcinna_pop <- read.csv("New Microsoft Excel Worksheet.csv", header = TRUE)
pcinna_pop <- pcinna_pop[pcinna_pop$Isolate %in% id, ]
pcinna_pop <- pcinna_pop[match(id, pcinna_pop$Isolate), ]

pop_cinna <- pcinna_pop$Country

pop_cinna_sojae <- as.factor(c(as.character(pop_cinna), "Psojae"))

vcf_cinna_sojae <- vcf
colnames(vcf_cinna_sojae@gt)[204] <- "Psojae"

vcf_cinna <- vcf[ , -ncol(vcf_cinna_sojae@gt)]


```


```{r}
vcf.genind <- vcfR2genind(vcf_cinna)
pop(vcf.genind) <- pop_cinna


tab <- mlg.table(vcf.genind)
mlg.crosspop(vcf.genind)


```



```{r}
library(ggtree)
library(ggrepel)
library(poppr)
library(dplyr)
library(adegenet)
library(ape)

vcf.gl <- vcfR2genlight(vcf_cinna)

tree_nj <- aboot(vcf.gl, tree = "nj", distance = bitwise.dist, sample = 10, showtree = F, cutoff = 50)

library(phangorn, quietly = TRUE)
tree_nj <- midpoint(tree_nj)


countryInfo <- split(tree_nj$tip.label, pop_cinna)
tree2 <- groupOTU(tree_nj, countryInfo)


tree2$tip.label <- paste(pcinna_pop$Country_code, pcinna_pop$MT, sep = "_")


ggtree(tree2, aes(color=group, label = node), layout="circular") + 
  geom_tiplab(size=3, aes(angle=angle)) 

ggtree(tree2, aes(color=group, label = node)) + 
  geom_tiplab(size=3) 

# ggtree(tree2, aes(color=group)) +
#   geom_tiplab(size=3) +
#   geom_text2(aes(subset=!isTip, label=node), hjust=-0.3) + geom_treescale()






## With PSojae

vcf.gl_sojae <- vcfR2genlight(vcf_cinna_sojae)

tree_nj_sojae <- aboot(vcf.gl_sojae, tree = "nj", distance = bitwise.dist, sample = 10, showtree = F, cutoff = 50)

library(phangorn, quietly = TRUE)

tree_nj_sojae <- ape::root(tree_nj_sojae, outgroup = "Psojae")


countryInfo <- split(tree_nj_sojae$tip.label, pop_cinna_sojae)
tree2_sojae <- groupOTU(tree_nj_sojae, countryInfo)


tree2_sojae$tip.label <- paste(pcinna_pop$Country_code, pcinna_pop$MT, sep = "_")
tree2_sojae$tip.label[203] <- "Psojae"

ggtree(tree2_sojae, aes(color=group, label = node), layout="circular") +
  geom_tiplab(size=3, aes(angle=angle))

# ggtree(tree2_sojae, aes(color=group, label = node)) + 
#   geom_tiplab(size=3) 





```

## RAXML

Preparing input file for RAXML

```{r}
all.vcf <- vcf_cinna_sojae

gt.filtered <- extract.gt(all.vcf, element = "GT")
gt.filtered[gt.filtered == "0/0"] <- 0
gt.filtered[gt.filtered == "0/1"] <- 1
gt.filtered[gt.filtered == "1/0"] <- 1
gt.filtered[gt.filtered == "1/1"] <- 2
gt.filtered[gt.filtered == "./."] <- "?"
gt.filtered[is.na(gt.filtered)] <- "?"

gt.df <- apply(gt.filtered, 2, function (x) paste(x, collapse = ""))
gt.df <- gsub(pattern = "/", "", gt.df, fixed = T)


#write.table(gt.df, file = "multistate.data.phy", quote = F)

#write.table(gt.df, file = "203isolates.phy", quote = F)
```

## RAXML tree

```{r}

library(ape)

tree1 <- read.tree("RAxML_bestTree.")

id <- unlist(strsplit(tree1$tip.label, split = ".fq"))
pcinna_pop <- read.csv("New Microsoft Excel Worksheet.csv", header = TRUE)
pcinna_pop <- pcinna_pop[pcinna_pop$Isolate %in% id, ]
pcinna_pop <- pcinna_pop[match(id, pcinna_pop$Isolate), ]

pcinna_pop <- pcinna_pop[-nrow(pcinna_pop),]

pop <- as.character(pcinna_pop$Country)
pop[] <- "Psojae"

pop <- as.factor(pop)

library(ggtree)
countryInfo <- split(tree1$tip.label, pop)
tree2 <- groupOTU(tree1, countryInfo)

tree2$tip.label <- as.character(pop)

ggtree(tree2, aes(color=group, label = node), layout="circular") + 
  geom_tiplab(size=5, aes(angle=angle))


ggtree(tree2, aes(color=group, label = node)) +  geom_tiplab(size=4)


ape::plot.phylo(tree2, use.edge.length = T)
axis(side = 2)

plot.phylo(tree2, x.lim = c(10,25))


plot.phylo(ladderize(tree2), use.edge.length = T)

axis(side = 2)
plot.phylo(tree2, y.lim = c(150,200))






```


## ADMIXTURE analysis

### Plotting cross validation error

```{r Cross validaion error, echo=TRUE, fig.align="center", fig.width=12, fig.height=12}

library(ggplot2)
cv <- read.table(file.path("./202Pcinna_ADMIXTURE/CV_error.txt")) 
cv <- cv[,c(3:4)]
colnames(cv) <- c("K", "Cross_Validation_Error")
cv <- cv[order(readr::parse_number(cv$K)), ]
cv$K <- factor(cv$K, levels = cv$K)

ggplot(data = cv, aes(K, Cross_Validation_Error)) + geom_point(size  = 5) +
  theme(axis.text.x = element_text(size = 15)) +
  theme(axis.text.y = element_text(size = 15))

```


This is very similar to STRUCTURE plot.

```{r, admixture}

library(reshape2)
qmat_files <- list.files("./202Pcinna_ADMIXTURE/qmatrices/")

source("admix_plot.R")

plot_list <- vector("list", length(qmat_files))

pop <- pop_cinna


for (k in 1:length(qmat_files)) {
    qmat <- read.table(file.path("./202Pcinna_ADMIXTURE/qmatrices/", qmat_files[k]))
    colnames(qmat) <- paste("Group", seq(1:ncol(qmat)), sep = ".")

    qmat <- cbind(pop, qmat)
    i <- sapply(qmat, is.factor)
    qmat[i] <- lapply(qmat[i], as.character)

    
    key <-  c("Australia" = "AUS", "Chile"= "CHL", "Dominican Republic" ="DOMREP",
              "France"= "FRA", "Italy"= "ITL","PNG"= "PNG", "Portugal"= "PORT",
              "South Africa"= "SA","USA"= "USA",
              "Taiwan"= "TWN","Vietnam"= "VNM", "Algeria" = "ALG",
              "Austria" = "AUST", "Hungary" = "HUN", "Spain" = "SPN", "Tunisia"="TUN", "UK"="UK")
    
    qmat$pop <- factor(key[qmat$pop], ordered = TRUE, levels = key)
    
    #qmat$pop <- factor(key[qmat$pop], levels = unique(qmat$pop)[c(2, 6, 7, 3, 4, 8, 11, 9, 1, 10, 5)], ordered = T)
     
    temp_plot <- admix_plot(qmat, horiz = F)
    temp_plot <- temp_plot + theme(axis.text.x = element_text(angle = 60, size = 15)) + theme_classic() 

    plot_list[[k]] <- temp_plot
    
} 

    

library(cowplot)

plot_grid(plotlist = plot_list[c(11, 13:14)], nrow = 3, ncol = 1)   
plot_grid(plotlist = plot_list[14:16], nrow = 3, ncol = 1)    

```



## convert to genlight and Minimum spanning network

```{r, eval=F}

vcf.gl <- vcfR2genlight(vcf_cinna)
#pop(vcf.gl) <- pop[-length(pop)]
pop(vcf.gl) <- pop_cinna

library(RColorBrewer)
library(pals)

myCol <- alphabet(n = 17) %>% setNames(popNames(vcf.gl))

msn <- poppr.msn(vcf.gl , distmat = bitwise.dist(vcf.gl ), palette = myCol, showplot = F)
set.seed(999)
plot_poppr_msn(vcf.gl , msn, inds = "na")


```

## DAPC

```{r, fig.align="center", fig.width=12, fig.height=12}

library(poppr)

vcf.gl <- vcfR2genlight(vcf_cinna)
pop(vcf.gl) <- pop_cinna

mydapc <- dapc(vcf.gl, pop = pop(vcf.gl), parallel = F,  n.pca = 50, n.da = 5)

scatter.dapc(mydapc, clabel = 0.75, pch=15:20, scree.pca = TRUE, scree.da = FALSE, 
        posi.pca = "topright", posi.leg = "topleft", legend = F, 
        cleg = 0.9, inset.solid = 1, xax = 1, yax = 2, cex.lab = 1, cex = 2, solid = 1, cstar = 0)



```